# Generated by Django 3.1.1 on 2020-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpage',
            name='title',
            field=models.CharField(default='furst', error_messages={'blank': 'This field has not to be blank', 'unique': 'This title is not unique'}, help_text='Must be a unique title', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
